#!/usr/bin/env python3
"""PreToolUse guard: apply the Bash guard's catastrophic checks to script FILES.

THE GAP (hooks/staged/script-file-bypasses-bash-guards.spec.md, staged 2026-08-12,
shipped 2026-09-06 — the spec is deleted on ship per /ship-hook; see git history)
    bash-security-guard.py inspects the COMMAND STRING. On 2026-08-12 the
    `${VAR:+set}${VAR:-NOT SET}` diagnostic it blocks inline was written to
    /tmp/claude/verify_probes.sh with the Write tool and run as
    `zsh /tmp/claude/verify_probes.sh`; the guard saw a path, two live API keys
    reached the transcript. Every command-string check had the same blind spot,
    and two pieces of standing guidance (SEC_REMEDY, the project CLAUDE.md) push
    work into it: "write it to a file and run it".

TWO LAYERS, ONE PREDICATE SET
    1. Write-time (PreToolUse Write|Edit|MultiEdit, via write-edit-dispatcher):
       when the target is script-like -- suffix .sh/.bash/.zsh/.ksh/.py, or the
       content opens with a shell/python shebang -- scan the written text. This is
       the earliest point at which refusing costs nothing.
    2. Execute-time (PreToolUse Bash, via bash-pretooluse-dispatcher): when the
       command runs a local script (`zsh x.sh`, `bash ./x.sh`, `source x.sh`,
       `./x.sh`, `python3 x.py`), resolve the path against the payload cwd and
       scan the file's bytes. Second layer only: a script assembled by several
       Edits or generated by a program has no single Write to inspect.

    Both layers run `bash_security_guard.CATASTROPHIC_CHECKS` -- the same tuple
    main() there iterates. Nothing is re-implemented here; a check added to the
    guard is inherited, and the two paths fail together or not at all (spec: "a
    COPY of those regexes is two-source drift").

WHAT IS SCANNED, PER LANGUAGE
    Shell (.sh/.bash/.zsh/.ksh, or a shell shebang): every logical line, after
    full-line and trailing comments are dropped and continuations are joined.
    Python (.py, or a python shebang): only the SHELL COMMANDS the file embeds --
    string literals handed to subprocess.*, os.system, os.popen, os.exec*,
    asyncio.create_subprocess_*, commands.*, pexpect.* -- extracted with `ast`
    (a regex fallback covers Edit fragments that do not parse). The predicates
    are shell grammar; run over arbitrary Python in the corpus replay they
    matched `print(env)` and `(set)` as "bare environment dump" 100 times,
    almost all in tests and security tooling that MENTION commands. Python-
    native exfiltration -- a credential file, a SECRET-shaped environment value
    or a keychain read reaching requests/urllib/httpx/socket -- is caught by
    the guard's `check_python_source_exfil` (ast, taint through assignments,
    SAFE_RE-exempt hosts), applied here to the whole file and by the guard to
    inline `python -c` bodies and heredocs.

STRENGTH  (CLAUDE_SCRIPT_CONTENT_GUARD = block | advise | off; default block)
    The spec's measurement gate ran on the author's full Claude Code transcript
    corpus on 2026-09-06 (bin/replay-script-content-guard.py); the fire rate and
    the pre-incident count are recorded in hooks/manifests/script-content-guard
    .yaml. `advise` emits the same text as additionalContext and exits 0; `off`
    is the mutation control the tests use to prove the known-positive can pass.

FAIL POSTURE
    Closed, like bash-security-guard: a guard that cannot load must not silently
    approve a script it was asked to inspect. Scope is narrow -- only script-like
    targets are examined, so a crash here cannot brick ordinary editing.

CONTRACT
    check(hook_input) -> (exit_code, stderr_payload, stdout_payload)   [dispatcher]
    main()            reads the payload from stdin                       [standalone]
"""
from __future__ import annotations

import ast
import importlib.util
import json
import os
import re
import sys
from pathlib import Path

HOOKS_DIR = Path(__file__).resolve().parent

SCRIPT_SUFFIXES = {".sh", ".bash", ".zsh", ".ksh", ".py"}
SHEBANG_RE = re.compile(r"\A#![^\n]*\b(?:sh|bash|zsh|ksh|dash|python[0-9.]*)\b")
_PY_SUFFIXES = {".py"}

# Execute-time: an interpreter or `source` followed by a script path, or a direct
# ./path invocation, at a command position.
_EXEC_RE = re.compile(
    r"(?:^|[;&|(]\s*|\bthen\s+|\bdo\s+|\bexec\s+|\bnohup\s+|\btime\s+)"
    r"(?:(?:ba|z|k|da)?sh|source|\.|python(?:3(?:\.\d+)?)?|pypy3?|uv\s+run|poetry\s+run\s+python3?)"
    r"\s+(?:-[A-Za-z]+\s+)*(?P<path>[^\s;&|<>()`$]+\.(?:sh|bash|zsh|ksh|py))(?=$|[\s;&|<>)])"
)
_DIRECT_RE = re.compile(
    r"(?:^|[;&|(]\s*|\bthen\s+|\bdo\s+|\bexec\s+|\bnohup\s+|\btime\s+)"
    r"(?P<path>\.{0,2}/[^\s;&|<>()`$]+\.(?:sh|bash|zsh|ksh|py))(?=$|[\s;&|<>)])"
)
MAX_SCAN_BYTES = 512 * 1024

_CONTINUATION_RE = re.compile(r"\\\r?\n[ \t]*")

# Python: which callees take a shell command, and (fallback) how to spot them and
# the string literals that follow when the source does not parse.
_EXEC_CALLEES = {
    "system", "popen", "run", "call", "check_call", "check_output", "Popen", "getoutput",
    "getstatusoutput", "create_subprocess_shell", "create_subprocess_exec", "spawn",
    "spawnu", "execv", "execve", "execvp", "execvpe", "execl", "execlp", "startfile",
}
_EXEC_CALL_FALLBACK_RE = re.compile(
    r"\b(?:subprocess\.\w+|os\.system|os\.popen|os\.exec\w*|commands\.\w+|pexpect\.\w+|"
    r"asyncio\.create_subprocess_\w+|(?<![\w.])(?:run|call|check_call|check_output|Popen|getoutput))"
    r"\s*\("
)
_PY_STRING_RE = re.compile(
    r"[rRbBfFuU]{0,2}(?:\"\"\"(?:.|\n)*?\"\"\"|'''(?:.|\n)*?'''|\"(?:[^\"\\\n]|\\.)*\"|'(?:[^'\\\n]|\\.)*')"
)


def _strength() -> str:
    value = (os.environ.get("CLAUDE_SCRIPT_CONTENT_GUARD") or "block").strip().lower()
    return value if value in {"block", "advise", "off"} else "block"


_GUARD = None


def _guard():
    """Load bash-security-guard.py once, by path (its filename has hyphens)."""
    global _GUARD
    if _GUARD is None:
        spec = importlib.util.spec_from_file_location(
            "bash_security_guard", HOOKS_DIR / "bash-security-guard.py")
        if spec is None or spec.loader is None:
            raise ImportError("bash-security-guard.py not found beside script-content-guard.py")
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        _GUARD = mod
    return _GUARD


def is_script_like(path: str, content: str) -> bool:
    suffix = Path(path).suffix.lower() if path else ""
    if suffix in SCRIPT_SUFFIXES:
        return True
    return bool(content) and bool(SHEBANG_RE.match(content.lstrip("\ufeff")))


def is_python(path: str, text: str) -> bool:
    first_line = (text or "").split("\n", 1)[0]
    return Path(path).suffix.lower() in _PY_SUFFIXES or (
        bool(SHEBANG_RE.match(text or "")) and "python" in first_line)


# ── shell ────────────────────────────────────────────────────────────────────

def _strip_trailing_comment(line: str) -> str:
    """Drop ` # ...` when the # is outside quotes. Cheap quote parity, not a parser."""
    in_s = in_d = False
    prev = ""
    for i, ch in enumerate(line):
        if ch == "'" and not in_d and prev != "\\":
            in_s = not in_s
        elif ch == '"' and not in_s and prev != "\\":
            in_d = not in_d
        elif ch == "#" and not in_s and not in_d and (i == 0 or line[i - 1] in " \t;"):
            return line[:i]
        prev = ch
    return line


def logical_lines(text: str, path: str = "") -> list[tuple[int, str]]:
    """Shell only: (line_number, statement) pairs with comments and continuations removed.

    Line numbers refer to the first physical line of each joined statement.
    """
    text = _CONTINUATION_RE.sub(" ", text or "")
    out: list[tuple[int, str]] = []
    for n, raw in enumerate(text.split("\n"), 1):
        stripped = raw.strip()
        if not stripped or stripped.startswith("#"):
            continue
        stmt = _strip_trailing_comment(raw).strip()
        if stmt:
            out.append((n, stmt))
    return out


# ── python ───────────────────────────────────────────────────────────────────

def _const_text(node) -> str | None:
    """A str constant, a list/tuple of them (joined as argv), or an f-string's
    constant parts (holes become $X) -- else None."""
    if isinstance(node, ast.Constant) and isinstance(node.value, str):
        return node.value
    if isinstance(node, ast.JoinedStr):
        parts = []
        for v in node.values:
            parts.append(v.value if isinstance(v, ast.Constant) and isinstance(v.value, str) else "$X")
        return "".join(parts)
    if isinstance(node, (ast.List, ast.Tuple)):
        items = [_const_text(e) for e in node.elts]
        if any(i is not None for i in items):
            return " ".join(i for i in items if i is not None)
    return None


def _unquote(literal: str) -> str:
    body = literal.lstrip("rRbBfFuU")
    if body[:3] in ('"""', "'''"):
        return body[3:-3]
    return body[1:-1]


def python_shell_statements(text: str) -> list[tuple[int, str]]:
    """(line_number, command_text) for every shell command literal handed to an exec API."""
    out: list[tuple[int, str]] = []
    try:
        tree = ast.parse(text or "")
    except (SyntaxError, ValueError):
        # A fragment (an Edit new_string) or broken source: fall back to literals
        # that follow an exec-looking call on the same line.
        for n, line in enumerate((text or "").split("\n"), 1):
            m = _EXEC_CALL_FALLBACK_RE.search(line)
            if not m:
                continue
            for lit in _PY_STRING_RE.finditer(line[m.end():]):
                out.append((n, _unquote(lit.group(0))))
        return out
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        fn = node.func
        name = fn.attr if isinstance(fn, ast.Attribute) else fn.id if isinstance(fn, ast.Name) else ""
        if name not in _EXEC_CALLEES:
            continue
        captured = _captures_output(name, node)
        candidates = list(node.args) + [k.value for k in node.keywords if k.arg in ("args", "cmd", "command")]
        for arg in candidates:
            cmd = _const_text(arg)
            if cmd and cmd.strip():
                # A captured command is the Python spelling of `X=$(cmd)`: its output
                # lands in a variable, not the transcript. Present it to the guard the
                # way the guard already exempts that shape at the shell level (store
                # readers match only at a top-level command position), so
                # `check_output(["security", ..., "-w"])` is not a "keychain dump".
                out.append((getattr(arg, "lineno", node.lineno), f"_=$({cmd})" if captured else cmd))
    return out


_CAPTURING_CALLEES = {"check_output", "getoutput", "getstatusoutput", "popen"}


def _captures_output(name: str, node) -> bool:
    if name in _CAPTURING_CALLEES:
        return True
    for k in node.keywords:
        if k.arg == "capture_output" and isinstance(k.value, ast.Constant) and k.value.value is True:
            return True
        if k.arg == "stdout" and not (isinstance(k.value, ast.Constant) and k.value.value is None):
            return True
    return False


# ── scan ─────────────────────────────────────────────────────────────────────

def scan_script(text: str, path: str = "") -> list[tuple[int, str]]:
    """Return [(line_number, BLOCKED reason)] for every statement a catastrophic check rejects."""
    guard = _guard()
    findings: list[tuple[int, str]] = []
    python = is_python(path, text)
    statements = python_shell_statements(text) if python else logical_lines(text, path)
    for lineno, stmt in statements:
        analysis = guard._normalize_for_matching(stmt)
        for check in guard.CATASTROPHIC_CHECKS:
            reason = check(analysis)
            if reason:
                findings.append((lineno, reason))
                break
    if python:
        # Python-native exfiltration (ast): the same predicate main() applies to
        # inline `python -c` bodies and heredocs, here over the whole file.
        reason = guard.check_python_source_exfil(text)
        if reason:
            m = re.search(r"at line (\d+)", reason)
            findings.append((int(m.group(1)) if m else 1, reason))
    return findings


def _written_texts(tool_name: str, tool_input: dict) -> list[str]:
    if tool_name == "Write":
        return [str(tool_input.get("content") or "")]
    if tool_name == "Edit":
        return [str(tool_input.get("new_string") or "")]
    if tool_name == "MultiEdit":
        return [str(e.get("new_string") or "") for e in tool_input.get("edits") or [] if isinstance(e, dict)]
    return []


def _resolve(path_text: str, cwd: str, command: str, guard) -> Path | None:
    p = os.path.expanduser(os.path.expandvars(path_text))
    base = cwd or os.getcwd()
    try:
        base = guard._resolve_effective_cwd(command, base) or base
    except Exception:
        pass
    candidate = Path(p) if os.path.isabs(p) else Path(base) / p
    try:
        candidate = candidate.resolve()
        if candidate.is_file() and candidate.stat().st_size <= MAX_SCAN_BYTES:
            return candidate
    except OSError:
        return None
    return None


def executed_scripts(command: str, cwd: str) -> list[Path]:
    guard = _guard()
    seen: list[Path] = []
    for rx in (_EXEC_RE, _DIRECT_RE):
        for m in rx.finditer(command):
            resolved = _resolve(m.group("path"), cwd, command, guard)
            if resolved and resolved not in seen:
                seen.append(resolved)
    return seen


def _message(where: str, findings: list[tuple[int, str]]) -> str:
    lineno, reason = findings[0]
    more = f" (+{len(findings) - 1} more)" if len(findings) > 1 else ""
    return (
        f"[script-content-guard] {where}, line {lineno}{more}: {reason} "
        f"The same check applies to command text and to script files; writing the "
        f"command to a file does not change the verdict."
    )


def _emit(strength: str, text: str) -> tuple[int, str | None, str | None]:
    if strength == "advise":
        advisory = text.replace("BLOCKED", "ADVISORY", 1)
        return (0, None, json.dumps({"hookSpecificOutput": {
            "hookEventName": "PreToolUse", "additionalContext": advisory}}))
    return (2, text, None)


def check(hook_input: dict) -> tuple[int, str | None, str | None]:
    """(exit_code, stderr_payload, stdout_payload) -- the write-edit-dispatcher contract."""
    strength = _strength()
    if strength == "off" or not isinstance(hook_input, dict):
        return (0, None, None)
    tool_name = str(hook_input.get("tool_name") or "")
    tool_input = hook_input.get("tool_input") or {}
    if not isinstance(tool_input, dict):
        return (0, None, None)

    if tool_name in {"Write", "Edit", "MultiEdit"}:
        path = str(tool_input.get("file_path") or "")
        texts = _written_texts(tool_name, tool_input)
        if not any(is_script_like(path, t) for t in texts):
            return (0, None, None)
        for text in texts:
            findings = scan_script(text, path)
            if findings:
                return _emit(strength, _message(f"script {path or '<unnamed>'}", findings))
        return (0, None, None)

    if tool_name in {"Bash", "PowerShell"}:
        command = str(tool_input.get("command") or "")
        if not command:
            return (0, None, None)
        for script in executed_scripts(command, str(hook_input.get("cwd") or "")):
            try:
                text = script.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            findings = scan_script(text, str(script))
            if findings:
                return _emit(strength, _message(f"executed script {script}", findings))
        return (0, None, None)

    return (0, None, None)


def main() -> None:
    try:
        raw = sys.stdin.read()
        if not raw.strip():
            sys.exit(0)
        hook_input = json.loads(raw)
    except (json.JSONDecodeError, ValueError):
        sys.exit(0)
    code, stderr_msg, stdout_msg = check(hook_input)
    if stderr_msg:
        print(stderr_msg, file=sys.stderr)
    if stdout_msg:
        print(stdout_msg)
    sys.exit(code)


if __name__ == "__main__":
    try:
        main()
    except SystemExit:
        raise
    except Exception as e:
        # FAIL-CLOSED, as bash-security-guard: an unavailable guard must not approve
        # the script it was asked to inspect. Scope is script-like targets only.
        print(f"[script-content-guard] BLOCKED: hook crashed ({e.__class__.__name__}: {e})",
              file=sys.stderr)
        sys.exit(2)
